apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  file-from-cfgmap: |
    {{ $parts := split "\n" .Values.fioconfig}}
    {{ range $lines := $parts}}
      {{ . | indent 4 }}{{ end }}