apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fio-perf-job.fullname" . }}
  labels:
    {{- include "fio-perf-job.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit | default 5 }}
  parallelism: {{ .Values.job.parallelism | default 5 }}
  {{ if not (empty .Values.job.ttlSecondsAfterFinished) }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{ end }}
  template:
    metadata:
      labels:
        {{- include "fio-perf-job.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: RUNTIME
          value: {{ .Values.env.runtime | quote}}
        volumeMounts:
        - name: fio-data
          mountPath: "/mnt/azurefiles"
        - name: mnt
          mountPath: /opt/config/fio.ini
          subPath: file-from-cfgmap
        command: 
        - "/opt/run.sh"
        - "/opt/config/fio.ini"
      volumes:
      - name: fio-data
        persistentVolumeClaim:
          claimName: pvc-{{.Release.Name | lower }}
      - name: mnt
        configMap:
          name: {{ .Release.Name }}-configmap
      restartPolicy: Never
  
      
