kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ .Release.Name | lower  }}
spec:
  accessModes:
    - {{ .Values.persistentvolumeclaim.spec.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentvolumeclaim.resources.requests.storage }}
  {{ if eq .Values.storageclass.parameters.protocol "nfs" }}
  storageClassName: "azurefile-csi-nfs"
  {{ else }}
  storageClassName: "azurefile-csi-premium"
  {{ end }}