apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: {{ .Values.storageclass.parameters.protocol | default "nfs" | quote}}
  skuName: {{ .Values.storageclass.parameters.skuName | default "Premium_LRS" | quote }} 
  enableLargeFileShares: {{ .Values.storageclass.parameters.enableLargeFileShares | default "true" | quote }}
  shareName: {{ .Values.storageclass.parameters.shareName | default "nfsshare" | quote }}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageclass.allowVolumeExpansion }}