apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-cfgmap
data:
  file-from-cfgmap: |
    [global]
    size=1g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k
    numjobs=4

    [reader1]
    rw=randread
    directory=/mnt/azurefiles