storageclass:
  parameters:
    protocol: nfs
    skuName: Premium_LRS  # available values: Premium_LRS, Premium_ZRS
    enableLargeFileShares: "true"
    shareName: "nfsshare"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true

persistentvolumeclaim:
  spec:
    accessModes: ReadWriteMany
  resources:
    requests:
      storage: 10Ti
    
job:
  backoffLimit: 5
  parallelism: 5
  ttlSecondsAfterFinished: 600

fioconfig: "fio.ini"