storageclass:
  parameters:
    protocol: smb # nfs or smb
    skuName: Premium_LRS  # available values: Premium_LRS, Premium_ZRS
    enableLargeFileShares: "true"
    shareName: "nfsshare"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true

persistentvolumeclaim:
  spec:
    accessModes: ReadWriteMany
  resources:
    requests:
      storage: 100Ti
    
job:
  backoffLimit: 5
  parallelism: 1
  ttlSecondsAfterFinished: 

fioconfig: "config/fio.ini"

image:
  repository: dapolloxp/fio
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "2.0"

env:
  runtime: 600