storageclass:
  parameters:
    protocol: smb # nfs or smb
    skuName: Premium_LRS  # available values: Premium_LRS, Premium_ZRS
    enableLargeFileShares: "true"
    shareName: "fileshare01" # or smbshare if using smbshare
    storageAccountName: "dapolinasafileperf"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true

aksRG: aks-rg

persistentvolumeclaim:
  spec:
    accessModes: ReadWriteMany
  resources:
    requests:
      storage: 100Ti
    
job:
  backoffLimit: 5
  parallelism: 10
  ttlSecondsAfterFinished: 600

fioconfig: "config/fio.ini"

image:
  repository: dapolloxp/fio
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "1.3"

env:
  runtime: 600