kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  storageClassName: "azurefile-csi-nfs"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-tester-read
  labels:
    app: fio-testing-read
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  
  selector:
    matchLabels:
      app: fio-testing-read
  template:
    metadata:
      labels:
        app: fio-testing-read
    spec:
      containers:
      - name: fio-container
        image: dapolinaaks.azurecr.io/fio:1.4
        volumeMounts:
        - name: fio-data
          mountPath: "/mnt/azurefiles"
        - name: mnt
          mountPath: /opt/config/fio.ini
          subPath: file-from-cfgmap
        command: 
        - "fio"
        - "/opt/config/fio.ini"
      volumes:
      - name: fio-data
        persistentVolumeClaim:
          claimName: pvc-azurefile-test
      - name: mnt
        configMap:
          name: fio-cfgmap
  
      
