kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile-fio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  storageClassName: "azurefile-csi-nfs"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-tester-write
  labels:
    app: fio-testing-write
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  parallelism: 15
  ttlSecondsAfterFinished: 240
  template:
    metadata:
      labels:
        app: fio-testing-read
    spec:
      containers:
      - name: fio-container
        image: dapolinaaks.azurecr.io/fio:1.6
        env:
        - name: RUNTIME
          value: "600"
        volumeMounts:
        - name: fio-data
          mountPath: "/mnt/azurefiles"
        - name: mnt
          mountPath: /opt/config/fio.ini
          subPath: file-from-cfgmap
        command: 
        - "/opt/run.sh"
        - "/opt/config/fio.ini"
      volumes:
      - name: fio-data
        persistentVolumeClaim:
          claimName: pvc-azurefile-fio
      - name: mnt
        configMap:
          name: fio-cfgmap
      restartPolicy: Never
  
      
