---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio-tester-read
  labels:
    app: fio-testing-read
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  
  selector:
    matchLabels:
      app: fio-testing-read
  template:
    metadata:
      labels:
        app: fio-testing-read
    spec:
      containers:
      - name: fio-container
        image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
        volumeMounts:
        - name: fio-data
          mountPath: "/mnt/azurefiles"
      volumes:
      - name: fio-data
        persistentVolumeClaim:
          claimName: pvc-azurefile-static
         
  
      
