apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-cfgmap
data:
  file-from-cfgmap: |
    [global]
    size=5g
    direct=1
    iodepth=256
    ioengine=libaio
    bs=4k
    numjobs=16

    [writer1]
    rw=randwrite
    directory=/mnt/azurefiles