---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile-static
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  storageClassName: azurefile-csi-nfs
  mountOptions:
    - nconnect=8
  csi:
    driver: file.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: unique-volumeid01
    volumeAttributes:
      resourceGroup: MC_formsai_dapolina_centralus # optional, only set this when storage account is not in the same resource group as agent node
      storageAccount: dapolinasa
      shareName: nfsshare  # only file share name, don't use full path
      protocol: nfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  volumeName: pv-azurefile-static
  storageClassName: "azurefile-csi-nfs"