apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: pv-blob1
    volumeAttributes:
      protocol: fuse
      resourceGroup: MC_aks-rg_dapolinafilesperf_centralus
      storageAccount: dapolinabloblperf01
      containerName: data
      AzureStorageAuthType: MSI
      AzureStorageIdentityObjectID: "9fe06b5d-1d4f-4cea-acab-cafe2c275a00"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob1
  storageClassName: azureblob-fuse-premium