apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: dapolinaaks.azurecr.io/fio:1.7
    name: test
    volumeMounts:
        - name: fio-data
          mountPath: "/mnt/azurefiles"
        - name: mnt
          mountPath: /opt/config/fio.ini
          subPath: file-from-cfgmap
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
      - name: fio-data
        persistentVolumeClaim:
          claimName: pvc-azurefile-fio
      - name: mnt
        configMap:
          name: fio-cfgmap
status: {}
