kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
  storageClassName: "azurefile-csi-nfs"