name: Docker Image CI

on:
  push:
    paths:
      - "deploy/dockerBuild/**"
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      version:
        description: "container version"
        default: "v1.0.0"
        type: "string"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Release Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ];
          then
            BUILD_VERSION=${{ github.event.inputs.version }}          
          else
            BUILD_VERSION=$(date --rfc-3339=date)       
          fi
          echo $BUILD_VERSION
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            deploy/dockerBuild:
            - 'deploy/dockerBuild/**'
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:deploy/dockerBuild"
          push: true
          tags: dapolloxp/fio:${{ env.BUILD_VERSION }}
