name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: cmd script
      run: echo "working dir" pwd;ls
    
    - name: Build the Docker image
      run: docker build . --file ./deploy/dockerBuild/Dockerfile --tag my-image-name:$(date +%s)
